bump mopidy-youtube from 3.3 to 3.4 to fix search
Trying to search Mopidy-YouTube gives the following error:
```
ERROR    2021-12-15 23:44:32,572 [7:YouTubeBackend-3] mopidy_youtube,
  search error "Extra data: line 1 column 280618 (char 280617)",
WARNING  2021-12-15 23:44:32,573 [7:Core-9] mopidy.core.library,
  YouTubeBackend does not implement library.search() with "exact" support. Please upgrade it.
```
current pinned version is 3.3, updating to version 3.4 fixes this.